development:
  adapter: postgresql
  database: my_database_development
  pool: 5
  timeout: 5000

#test:
#  adapter: sqlite3
#  pool: 5
#  timeout: 5000
#  database: db/test.sqlite3
test:
  adapter: postgresql
  database: my_database_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: my_database_production
  pool: 5
  timeout: 5000
